language: android
jdk: oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

env:
 global:
 - ANDROID_API=28
 - ANDROID_BUILD_TOOLS=28.0.3
 - TRAVIS_REPO=IYCLLC/android-NM

android:
  components:
  - android-${ANDROID_API}
  - build-tools-${ANDROID_BUILD_TOOLS}
  - extra
stages:
  - name: test
    if: type = pull_request OR type = push AND ( /^release\/production\*?/ OR /^release\/qa\*?/ OR /^release\/uat\*?/ )
  - name: deploy-production
    if: type = push AND branch =~ /^release\/production\*?/
  - name: deploy-qa
    if: type = push AND branch =~ /^release\/qa\*?/
  - name: deploy-uat
    if: type = push AND branch =~ /^release\/uat\*?/
jobs:
  include:
    - stage: test
      script:
        - ./gradlew clean assembleDebug check test -x lint
